main: main.cpp Operate.cpp Controller.cpp Table.cpp BPTree.h BPTreeNode.h Controller.h DataBase.h OOPDB.h Operate.h SubClass.h Table.h
	g++ -o main main.cpp Controller.cpp Operate.cpp Table.cpp -std=c++14
